server:
  port: 8084
spring:
  application:
    name: configurationserver
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wmuhea/Kemis-Shop-Microservice.git
          search-paths: configuration-files,accountservice,catalogservice,orderservice,clientproxy


  # The following two are used after config: server -> to indicate usage of the resources folder of the config server
  # native indicates -> that we do not use any repository for storing the configuration files
  #       native:
  #         search-locations: file:///Users/wontgn/Documents/Study/StudyCodes/MyProjects/Shopping-Cart-Micro/ProjectFolders/configurationserver/src/main/resources/config/authorizationservice